# Seconda serie «Primo soccorso passo passo» (novembre-dicembre) + speciale Giornata del volontariato.
# Fonti: linee guida ERC/IRC 2025 (BLS, PBLS, primo soccorso), libro ERC 2025 per i cittadini.
from contenuti import S, FINE, U12
SER = 'Primo soccorso passo passo · 2ª serie'
def E(nome, num, scene=None, **kw):
    return dict(nome=nome, num=num, tot=13, serie=SER, scene=scene, **kw)
V2 = {
'convulsioni': E('Convulsioni', 1, [
  S('Convulsioni', ['Mantieni','la *calma*.'], 'Crisi convulsiva: fa paura, ma di solito finisce da sola in pochi minuti. Ecco cosa fare.', 'convulsione'),
  S('Spazio intorno', ['Allontana','gli *oggetti*.'], 'Allontana gli oggetti pericolosi e fai spazio intorno alla persona.', 'conv-spazio', [['Spazio libero', .7]]),
  S('Non trattenerlo', ['Non','*bloccarlo*.'], 'Non trattenere i movimenti: potresti fargli male, e non fermi la crisi.', 'conv-no-tenere', [['Non trattenere', .3]]),
  S('La testa', ['Proteggi','la *testa*.'], 'Metti qualcosa di morbido sotto la testa, come una giacca piegata, e allenta il colletto.', 'conv-cuscino', [['Giacca sotto la testa', .45], ['Colletto allentato', .85]]),
  S('Niente in bocca', ['Niente','in *bocca*.'], 'Non mettere niente in bocca: né dita, né oggetti, né acqua. La lingua non si ingoia.', 'conv-bocca', [['Niente dita', .2], ['Niente oggetti', .35], ['Niente acqua', .5]]),
  S('Il tempo', ['Guarda','l\'*orologio*.'], 'Guarda l\'ora in cui inizia. Se dura più di cinque minuti, chiama subito '+U12+'.', 'timer5c', [['Più di 5 minuti: 112', .75, 1]],
    sub='Guarda l\'ora in cui inizia. Se dura più di 5 minuti, chiama subito il 112.'),
  S('Quando chiamare', ['Chiama','il *112*.'], 'Chiama '+U12+' anche se è la prima crisi, se si è ferito, se è incinta, se le crisi si ripetono, o se non si riprende.', 'telefono', [['Prima crisi', .2], ['Ferito', .35], ['Incinta', .48], ['Crisi ripetute', .65], ['Non si riprende', .88]],
    sub='Chiama il 112 anche se è la prima crisi, se si è ferito, se è incinta, se le crisi si ripetono, o se non si riprende.'),
  S('Dopo la crisi', ['Su un','*fianco*.'], 'Quando i movimenti finiscono, controlla il respiro. Se respira normalmente, mettilo su un fianco e resta con lui: sarà confuso e stanco.', 'pls', [['Controlla il respiro', .25], ['Su un fianco', .55], ['Resta con lui', .8]]),
  S('Attenzione', ['Non respira?','*Rianima*.'], 'Se dopo i movimenti non respira normalmente, può essere un arresto cardiaco: chiama '+U12+' e inizia la rianimazione.', 'rcp-mini', [['Chiama il 112', .7, 1], ['Rianimazione', .9]],
    sub='Se dopo i movimenti non respira normalmente, può essere un arresto cardiaco: chiama il 112 e inizia la rianimazione.'),
  FINE]),
'incidente-stradale': E('Incidente stradale', 2, [
  S('Incidente stradale', ['Prima di tutto,','la *sicurezza*.'], 'Incidente stradale: per aiutare davvero, prima devi restare al sicuro.', 'incidente'),
  S('Fermati bene', ['Frecce e','*giubbotto*.'], 'Fermati in un posto sicuro, accendi le quattro frecce e indossa il giubbotto catarifrangente prima di scendere.', 'giubbotto', [['Quattro frecce', .4], ['Giubbotto', .75]]),
  S('Il triangolo', ['Segnala','il *pericolo*.'], 'Metti il triangolo ben prima dell\'incidente, ad almeno cinquanta metri, per avvisare chi arriva.', 'triangolo', [['Almeno 50 metri', .6]],
    sub='Metti il triangolo ben prima dell\'incidente, ad almeno 50 metri, per avvisare chi arriva.'),
  S('Motori spenti', ['Spegni','i *motori*.'], 'Se puoi farlo senza rischi, spegni il motore delle auto coinvolte. E niente sigarette.', 'chiave', [['Motore spento', .5], ['Niente sigarette', .85]]),
  S('Chiama', ['Chiama','il *112*.'], 'Chiama '+U12+': di\' dove sei, quanti sono i feriti, e se qualcuno è incastrato.', 'telefono-posizione', [['Dove', .35], ['Quanti feriti', .6], ['Incastrati?', .85]],
    sub='Chiama il 112: di\' dove sei, quanti sono i feriti, e se qualcuno è incastrato.'),
  S('Non spostarli', ['Lascialo','dov\'è.'], 'Non spostare i feriti, a meno che non ci sia un pericolo immediato, come un incendio.', 'non-muovere', [['Non spostare', .3], ['Solo se c\'è pericolo', .8]]),
  S('Il casco', ['Il casco','*resta*.'], 'Al motociclista non togliere il casco: si toglie solo se non respira, e meglio se lo fa chi ha imparato come.', 'casco', [['Non togliere il casco', .3]]),
  S('Stagli vicino', ['Parlagli','e *coprilo*.'], 'Parla con i feriti, rassicurali e coprili per tenerli al caldo, finché arrivano i soccorsi.', 'coperta', [['Rassicura', .3], ['Copri', .7]]),
  S('Se non respira', ['Pronto alla','*rianimazione*.'], 'Se un ferito non risponde e non respira normalmente, inizia la rianimazione, seguendo l\'operatore del '+U12[3:]+'.', 'rcp-mini', [['Rianimazione', .5]],
    sub='Se un ferito non risponde e non respira normalmente, inizia la rianimazione, seguendo l\'operatore del 112.'),
  FINE]),
'svenimento': E('Svenimento', 3, [
  S('Svenimento', ['Giù, e','gambe *su*.'], 'Svenimento: di solito passa in fretta, ma bisogna sapere cosa fare.', 'svenimento'),
  S('I segni prima', ['Sta per','*svenire*?'], 'Prima di svenire spesso si diventa pallidi e sudati, con nausea, vista annebbiata e un ronzio nelle orecchie.', 'pre-sincope', [['Pallore', .15], ['Sudore', .25], ['Vista annebbiata', .55], ['Ronzio', .85]]),
  S('Le contromanovre', ['Gambe','*incrociate*.'], 'Se senti che stai per svenire, incrocia le gambe e stringi forte i muscoli, oppure accovacciati. Meglio ancora, sdraiati.', 'contromanovre', [['Gambe incrociate e strette', .3], ['Accovacciati', .6], ['Sdraiati', .88]]),
  S('Se sviene', ['Sdraiato,','gambe *su*.'], 'Se sviene, mettilo sdraiato e sollevagli le gambe: il sangue torna alla testa.', 'gambe-su', [['Sdraiato', .3], ['Gambe sollevate', .7]]),
  S('Aria', ['Aria','e *spazio*.'], 'Allenta i vestiti stretti, fai spazio intorno e lascia circolare l\'aria.', 'seduto', [['Vestiti allentati', .3], ['Spazio', .7]]),
  S('Un minuto', ['Si riprende','in *fretta*.'], 'Di solito si riprende in meno di un minuto. Se non si riprende, controlla il respiro e chiama '+U12+'.', 'timer1', [['Meno di 1 minuto', .3], ['Non si riprende: 112', .8, 1]],
    sub='Di solito si riprende in meno di un minuto. Se non si riprende, controlla il respiro e chiama il 112.'),
  S('Piano piano', ['Rialzati','*piano*.'], 'Quando sta meglio, fallo rialzare piano: prima seduto, poi in piedi. Se si alza di colpo, può svenire di nuovo.', 'seduto', [['Prima seduto', .3], ['Poi in piedi', .5]]),
  S('Dal medico', ['Quando','*preoccuparsi*.'], 'Chiama '+U12+' se è svenuto durante uno sforzo, se ha avuto dolore al petto o il cuore che batte forte, o se si è ferito cadendo.', 'telefono', [['Durante uno sforzo', .3], ['Dolore al petto', .5], ['Palpitazioni', .65], ['Ferito', .88]],
    sub='Chiama il 112 se è svenuto durante uno sforzo, se ha avuto dolore al petto o il cuore che batte forte, o se si è ferito cadendo.'),
  FINE]),
'soffocamento-lattante': E('Soffocamento nel lattante', 4, [
  S('Lattante', ['Se un neonato','*soffoca*.'], 'Soffocamento nel lattante, cioè sotto l\'anno di età: le manovre sono diverse dall\'adulto.', 'lattante'),
  S('Riconosci', ['Non piange,','non *respira*.'], 'Se il bambino non riesce a piangere, a tossire o a respirare, e diventa blu, l\'ostruzione è grave.', 'lattante-blu', [['Non piange', .2], ['Non respira', .5], ['Diventa blu', .8]]),
  S('Se tossisce', ['Lascialo','*tossire*.'], 'Se tossisce o piange, lascialo tossire e tienilo d\'occhio. Non infilare le dita in bocca alla cieca.', 'no-dita', [['Lascialo tossire', .3], ['Niente dita in bocca', .75]]),
  S('Chiama', ['Chiama','il *112*.'], 'Fai chiamare '+U12+', o chiama tu con il vivavoce, e inizia subito le manovre.', 'telefono', [['Chiama il 112', .3, 1], ['Vivavoce', .6]],
    sub='Fai chiamare il 112, o chiama tu con il vivavoce, e inizia subito le manovre.'),
  S('5 pacche', ['Sulla','*schiena*.'], 'Mettilo a pancia in giù sul tuo avambraccio, con la testa più in basso, sostenendo il mento. Dai fino a cinque pacche decise tra le scapole.', 'lattante-pacche', [['Testa in basso', .3], ['Fino a 5 pacche', .8]]),
  S('5 compressioni', ['Sul','*torace*.'], 'Se non basta, giralo a pancia in su, sempre con la testa in basso. Con i due pollici al centro del torace, fai fino a cinque compressioni.', 'lattante-torace', [['A pancia in su', .25], ['Due pollici', .6], ['Fino a 5', .85]]),
  S('Alterna', ['5 e 5,','senza *fermarti*.'], 'Continua alternando cinque pacche e cinque compressioni, finché l\'oggetto non esce o arrivano i soccorsi.', 'alterna-lattante', [['Alterna 5 e 5', .6]]),
  S('Se non risponde', ['5 soffi e','*rianimazione*.'], 'Se perde conoscenza, mettilo su un piano rigido, dai cinque soffi nella bocca e nel naso e inizia la rianimazione.', 'rcp-lattante-mini', [['5 soffi', .5], ['Rianimazione', .85]]),
  S('Previeni', ['Pezzi','*piccoli*.'], 'Per prevenire: tieni lontani gli oggetti piccoli, e taglia per lungo in quattro parti gli alimenti tondi come uva, pomodorini e olive.', 'uva', [['Oggetti piccoli', .25], ['Uva tagliata in 4', .75]]),
  FINE]),
'rianimazione-bambino': E('Rianimazione nel bambino', 5, bpm=110, scene=[
  S('Bambini', ['Rianimare','un *bambino*.'], 'Rianimazione nel lattante e nel bambino: le differenze con l\'adulto, passo passo.', 'bimbo-cuore'),
  S('Riconosci', ['Risponde?','*Respira*?'], 'Chiamalo e toccalo con delicatezza. Non risponde e non respira normalmente? Devi agire subito.', 'respiro-bimbo', [['Non risponde', .4], ['Non respira normalmente', .8]]),
  S('Chiama', ['Chiama','il *112*.'], 'Chiama '+U12+' con il vivavoce: l\'operatore ti guida. Se sei solo e senza telefono, fai prima un minuto di rianimazione, poi vai a chiamare.', 'telefono', [['Chiama il 112', .2, 1], ['Senza telefono: 1 minuto, poi chiama', .85]],
    sub='Chiama il 112 con il vivavoce: l\'operatore ti guida. Se sei solo e senza telefono, fai prima un minuto di rianimazione, poi vai a chiamare.'),
  S('5 soffi', ['Prima,','5 *soffi*.'], 'Nei bambini si comincia con cinque soffi. Testa leggermente indietro, e soffia per un secondo, finché il torace si alza. Nel lattante, copri bocca e naso.', 'ventila5', [['5 soffi', .2], ['Il torace si alza', .6], ['Lattante: bocca e naso', .9]]),
  S('Le mani', ['Due pollici','o una *mano*.'], 'Nel lattante, circonda il torace con le mani e spingi con i due pollici. Nel bambino, usa una mano o due, secondo la sua corporatura.', 'mani-bimbo', [['Lattante: due pollici', .3], ['Bambino: una o due mani', .8]]),
  S('Compressioni', ['Segui il','*ritmo*.'], 'Spingi per un terzo del torace, circa quattro centimetri nel lattante, cinque nel bambino. Segui il ritmo.', 'rcp-lattante-sim', [['Un terzo del torace', .3], ['110 al minuto', .9]], conta=30,
    sub='Spingi per un terzo del torace, circa 4 cm nel lattante, 5 nel bambino. Segui il ritmo.'),
  S('30 e 2', ['Compressioni','e *soffi*.'], 'Poi due soffi, e ancora trenta compressioni. Chi ha fatto un corso pediatrico usa quindici e due. Se proprio non riesci a soffiare, continua con le compressioni.', 'ventila-bimbo', [['30 e 2', .2], ['Con il corso: 15 e 2', .55], ['Almeno le compressioni', .88]],
    sub='Poi 2 soffi, e ancora 30 compressioni. Chi ha fatto un corso pediatrico usa 15 e 2. Se proprio non riesci a soffiare, continua con le compressioni.'),
  S('Il DAE', ['Anche nei','*bambini*.'], 'Il defibrillatore si usa anche nei bambini. Sotto i venticinque chili, se c\'è, scegli la modalità pediatrica, e attacca le piastre una davanti e una dietro.', 'dae-bimbo', [['Modalità pediatrica', .4], ['Davanti e dietro', .8]],
    sub='Il defibrillatore si usa anche nei bambini. Sotto i 25 kg, se c\'è, scegli la modalità pediatrica, e attacca le piastre una davanti e una dietro.'),
  S('Non fermarti', ['Fino ai','*soccorsi*.'], 'Non fermarti finché non arrivano i soccorsi, o finché il bambino non si sveglia e respira normalmente.', 'bimbo-continua', [['Non fermarti', .4]]),
  FINE]),
'fratture': E('Fratture e distorsioni', 6, [
  S('Fratture', ['Ferma,','non *raddrizzare*.'], 'Fratture e distorsioni: cosa fare dopo una caduta o un colpo.', 'osso'),
  S('I segni', ['Come','*riconoscerla*.'], 'Dolore forte, gonfiore, un livido, una forma strana, o la parte che non si riesce a muovere.', 'arto-gonfio', [['Dolore', .15], ['Gonfiore', .3], ['Forma strana', .55], ['Non si muove', .85]]),
  S('Non raddrizzare', ['Lascialo','*com\'è*.'], 'Non cercare di raddrizzare l\'arto e non farlo muovere: potresti peggiorare la lesione.', 'arto-no', [['Non raddrizzare', .3], ['Non muovere', .6]]),
  S('Sostieni', ['Ferma','la *parte*.'], 'Sostieni la parte nella posizione in cui si trova, con le mani, con un cuscino o con una sciarpa a fascia per il braccio.', 'fascia', [['Nella posizione trovata', .35], ['Fascia per il braccio', .85]]),
  S('Il freddo', ['Ghiaccio','nel *panno*.'], 'Metti del ghiaccio avvolto in un panno, mai direttamente sulla pelle, per una ventina di minuti.', 'ghiaccio-arto', [['Mai sulla pelle', .45], ['Circa 20 minuti', .85]],
    sub='Metti del ghiaccio avvolto in un panno, mai direttamente sulla pelle, per una ventina di minuti.'),
  S('Frattura esposta', ['Copri,','non *spingere*.'], 'Se l\'osso esce dalla pelle, copri con una garza pulita, senza spingerlo dentro, e premi intorno se sanguina.', 'esposta', [['Garza pulita', .3], ['Non spingere l\'osso', .6]]),
  S('Quando chiamare', ['Chiama','il *112*.'], 'Chiama '+U12+' per fratture esposte, per l\'anca, il femore, la schiena o il collo, se il dolore è fortissimo, o se mano o piede sono freddi e senza sensibilità.', 'telefono', [['Esposta', .15], ['Anca o femore', .3], ['Schiena o collo', .45], ['Mano o piede freddi', .85]],
    sub='Chiama il 112 per fratture esposte, per l\'anca, il femore, la schiena o il collo, se il dolore è fortissimo, o se mano o piede sono freddi e senza sensibilità.'),
  S('Distorsione', ['Riposo','e *ghiaccio*.'], 'Per una distorsione: riposo, ghiaccio nel panno e parte sollevata. Se il dolore non passa, fatti vedere da un medico.', 'distorsione', [['Riposo', .15], ['Ghiaccio', .3], ['Sollevato', .5], ['Dal medico', .85]]),
  FINE]),
'freddo': E('Ipotermia e congelamento', 7, [
  S('Freddo', ['Quando il freddo','è *pericoloso*.'], 'Ipotermia: quando il corpo perde più calore di quanto ne produce.', 'termometro'),
  S('I segni', ['Brividi,','poi *confusione*.'], 'Brividi forti, pelle fredda e pallida, mani impacciate. Poi confusione e sonnolenza. Se smette di tremare, è grave.', 'brividi', [['Brividi', .15], ['Pelle fredda', .3], ['Confusione', .55], ['Smette di tremare', .9]]),
  S('Al riparo', ['Al','*caldo*.'], 'Portalo al riparo, al caldo, muovendolo con delicatezza, senza farlo camminare se è molto debole.', 'casa-caldo', [['Al riparo', .3], ['Con delicatezza', .75]]),
  S('Vestiti bagnati', ['Asciutto','e *coperto*.'], 'Togli i vestiti bagnati, asciugalo e coprilo con coperte asciutte, anche la testa. Isola il corpo dal pavimento freddo.', 'coperta', [['Via i vestiti bagnati', .25], ['Coperte asciutte', .5], ['Anche la testa', .7]]),
  S('Da bere', ['Caldo,','*niente* alcol.'], 'Se è sveglio e riesce a deglutire, dagli una bevanda calda e zuccherata. Niente alcol: fa perdere ancora più calore.', 'tazza', [['Bevanda calda', .3], ['Niente alcol', .75]]),
  S('Quando chiamare', ['Chiama','il *112*.'], 'Se è confuso, sonnolento o non trema più, chiama '+U12+' e tienilo sdraiato. Se non respira normalmente, inizia la rianimazione.', 'telefono', [['Confuso o sonnolento', .3, 1], ['Non respira: rianimazione', .85]],
    sub='Se è confuso, sonnolento o non trema più, chiama il 112 e tienilo sdraiato. Se non respira normalmente, inizia la rianimazione.'),
  S('Congelamento', ['Non','*strofinare*.'], 'Dita, orecchie o naso bianchi e insensibili? Non strofinare e non scaldare con fuoco o stufe: si rischiano ustioni. Scalda con il calore del corpo e vai in ospedale.', 'mano-gelo', [['Non strofinare', .3], ['Niente fuoco diretto', .55], ['Calore del corpo', .8]]),
  S('Chi rischia', ['Guarda chi','è *solo*.'], 'Anziani soli, persone senza casa, chi ha bevuto. Se vedi qualcuno in difficoltà al freddo, non tirare dritto: chiama '+U12+'.', 'persone-freddo', [['Anziani', .15], ['Senza casa', .3], ['Non tirare dritto', .85, 1]],
    sub='Anziani soli, persone senza casa, chi ha bevuto. Se vedi qualcuno in difficoltà al freddo, non tirare dritto: chiama il 112.'),
  FINE]),
'monossido': E('Monossido di carbonio', 8, [
  S('Monossido', ['Il gas che','non si *sente*.'], 'Monossido di carbonio: non ha odore né colore, e ogni inverno fa vittime anche in casa.', 'co'),
  S('Da dove viene', ['Stufe, camini,','*caldaie*.'], 'Si forma quando qualcosa brucia male: stufe, camini, caldaie, scaldabagni, bracieri, generatori e motori accesi al chiuso.', 'co-fonti', [['Stufe', .15], ['Camini', .22], ['Caldaie', .3], ['Bracieri', .55], ['Motori al chiuso', .85]]),
  S('I segni', ['Mal di testa,','*nausea*.'], 'Mal di testa, nausea, vertigini, sonnolenza. Se stanno male più persone in casa, o anche gli animali, pensa subito al monossido.', 'co-segni', [['Mal di testa', .1], ['Nausea', .2], ['Vertigini', .3], ['Più persone', .7]]),
  S('Fuori', ['Apri','ed *esci*.'], 'Apri porte e finestre ed esci all\'aria aperta. Spegni l\'apparecchio solo se puoi farlo subito e senza rischi.', 'finestra', [['Apri tutto', .25], ['Esci', .5], ['Spegni, se sicuro', .85]]),
  S('Chiama', ['Chiama','il *112*.'], 'Chiama '+U12+', anche se all\'aria aperta ti senti meglio: l\'intossicazione va curata.', 'telefono', [['Chiama il 112', .3, 1], ['Anche se stai meglio', .75]],
    sub='Chiama il 112, anche se all\'aria aperta ti senti meglio: l\'intossicazione va curata.'),
  S('Se non risponde', ['Pronto alla','*rianimazione*.'], 'Se una persona non risponde e non respira normalmente, portala fuori solo se non rischi anche tu, e inizia la rianimazione.', 'rcp-mini', [['Senza rischi per te', .5], ['Rianimazione', .85]]),
  S('Previeni', ['Controlli','e *rilevatore*.'], 'Fai controllare ogni anno caldaia, stufe e canne fumarie, e installa un rilevatore di monossido.', 'rilevatore', [['Controllo ogni anno', .35], ['Rilevatore di monossido', .8]]),
  S('Mai', ['Mai','al *chiuso*.'], 'Mai bracieri o generatori in casa, mai il forno a gas per scaldarsi, mai il motore acceso in garage chiuso.', 'no-braciere', [['Niente bracieri', .2], ['Niente forno per scaldarsi', .5], ['Niente motore in garage', .85]]),
  FINE]),
'giornata-volontariato': dict(nome='Giornata del volontariato', num=0, brano='morning', serie='Speciale · 5 dicembre, Giornata del volontariato',
  card=dict(s='Diventa volontario · iscrizioni', tel='328 8105399'), scene=[
  S('5 dicembre', ['Giornata del','*volontariato*.'], 'Il cinque dicembre è la Giornata internazionale del volontariato. Oggi diciamo grazie.', 'mani-cuore', sub='Il 5 dicembre è la Giornata internazionale del volontariato. Oggi diciamo grazie.'),
  S('Grazie', ['A chi c\'è,','*ogni giorno*.'], 'Grazie ai volontari della Misericordia di Ariccia, che regalano il loro tempo a chi ha bisogno. Che Iddio ve ne renda merito.', 'grazie', [['Che Iddio ve ne renda merito', .8]]),
  S('Trasporti', ['Accanto a chi','si *cura*.'], 'Accompagnano chi deve curarsi, in ambulanza, in auto o con i mezzi attrezzati per la sedia a rotelle.', 'trasporti', [['Ambulanza', .3], ['Mezzi attrezzati', .8]]),
  S('Famiglie', ['Ascolto','e *spesa*.'], 'Con il Centro di Ascolto e il Banco Alimentare accolgono le famiglie in difficoltà.', 'spesa', [['Centro di Ascolto', .4], ['Banco Alimentare', .75]]),
  S('Eventi', ['Alle feste','del *territorio*.'], 'Garantiscono l\'assistenza sanitaria a gare, feste e manifestazioni dei Castelli Romani.', 'eventi', [['Gare', .3], ['Feste', .45], ['Manifestazioni', .7]]),
  S('Chi può', ['Dai 16','agli *80 anni*.'], 'Possono diventare volontari donne e uomini dai sedici agli ottant\'anni. Non servono competenze: la formazione la facciamo insieme.', 'persone', [['Dai 16 agli 80 anni', .3], ['Nessuna competenza', .7]],
    sub='Possono diventare volontari donne e uomini dai 16 agli 80 anni. Non servono competenze: la formazione la facciamo insieme.'),
  S('Come iniziare', ['Tre passi,','*insieme*.'], 'Contattaci o passa in sede, presenta la domanda, e inizia il percorso con noi, passo dopo passo.', 'passi3', [['Contattaci', .2], ['La domanda', .5], ['Il percorso', .8]]),
  dict(chip='Diventa volontario', title=['C\'è posto','anche per *te*.'], voce='C\'è posto anche per te. Chiamaci, o passa a trovarci in sede, ad Ariccia.', ill='fine', tags=[]),
  ]),
'asma': E('Crisi d\'asma', 9, [
  S('Asma', ['Quando manca','il *respiro*.'], 'Crisi d\'asma: i bronchi si chiudono e l\'aria fatica a uscire.', 'polmoni'),
  S('I segni', ['Fischi','e *fiato corto*.'], 'Fiato corto, fischi nel respiro, tosse, senso di oppressione al petto. Nei casi gravi non riesce a parlare.', 'asma-segni', [['Fiato corto', .15], ['Fischi', .3], ['Tosse', .45], ['Non parla', .85]]),
  S('La posizione', ['Seduto,','*in avanti*.'], 'Fallo stare seduto, leggermente in avanti, con le braccia appoggiate. Non farlo sdraiare.', 'seduto-avanti', [['Seduto in avanti', .3], ['Non sdraiato', .8]]),
  S('La calma', ['Respira','con *calma*.'], 'Resta calmo e aiutalo a respirare lentamente: l\'agitazione peggiora la crisi.', 'respira-calmo', [['Respiri lenti', .6]]),
  S('Lo spray', ['Il suo','*spray*.'], 'Se ha il suo spray per la crisi, aiutalo a usarlo, come gli ha spiegato il medico.', 'inalatore', [['Il suo spray', .3], ['Come da medico', .75]]),
  S('Quando chiamare', ['Chiama','il *112*.'], 'Chiama '+U12+' se lo spray non funziona, se non riesce a parlare, se le labbra diventano blu, o se è molto stanco o sonnolento.', 'telefono', [['Lo spray non basta', .25], ['Non parla', .45], ['Labbra blu', .65], ['Sonnolento', .88]],
    sub='Chiama il 112 se lo spray non funziona, se non riesce a parlare, se le labbra diventano blu, o se è molto stanco o sonnolento.'),
  S('Allergia', ['Gonfiore?','*Adrenalina*.'], 'Se la crisi arriva con gonfiore di labbra o lingua dopo un cibo o una puntura, può essere anafilassi: serve l\'adrenalina.', 'adrenalina', [['Anafilassi', .6]]),
  S('Se non respira', ['Pronto alla','*rianimazione*.'], 'Se perde conoscenza e non respira normalmente, inizia la rianimazione.', 'rcp-mini', [['Rianimazione', .7]]),
  FINE]),
'batterie': E('Batterie a bottone e calamite', 10, [
  S('Batterie a bottone', ['Piccole, ma','*pericolose*.'], 'Batterie a bottone: se un bambino ne ingoia una, è un\'emergenza.', 'batteria'),
  S('Perché', ['In poche ore','*brucia*.'], 'La batteria si ferma nell\'esofago e, in poche ore, può bruciarlo dall\'interno.', 'esofago', [['In poche ore', .6]]),
  S('I segni', ['Spesso','*nessuno*.'], 'Spesso all\'inizio non ci sono segni. A volte tosse, bava, dolore, vomito, o rifiuta di mangiare.', 'bimbo-dubbio', [['Spesso nessun segno', .2], ['Tosse o bava', .5], ['Rifiuta il cibo', .9]]),
  S('Anche il dubbio', ['Subito','in *ospedale*.'], 'Anche solo il dubbio basta: chiama '+U12+' o vai subito al pronto soccorso. Non aspettare i sintomi.', 'trasporti', [['Basta il dubbio', .2, 1], ['Non aspettare', .8]],
    sub='Anche solo il dubbio basta: chiama il 112 o vai subito al pronto soccorso. Non aspettare i sintomi.'),
  S('Cosa non fare', ['Niente','*vomito*.'], 'Non farlo vomitare, e non dargli da mangiare o da bere, se non lo dicono i medici o il Centro Antiveleni.', 'no-vomito', [['Niente vomito', .2], ['Niente cibo', .45]]),
  S('La confezione', ['Porta','la *confezione*.'], 'Porta con te la confezione, o una batteria uguale: aiuta i medici a capire.', 'confezione-batt', [['Confezione o batteria uguale', .6]]),
  S('Calamite', ['Due calamite,','*doppio* rischio.'], 'Anche le piccole calamite sono pericolose: se ne ingoia due o più, si attraggono attraverso l\'intestino e lo danneggiano.', 'calamite', [['Due o più calamite', .6]]),
  S('Previeni', ['Vano','*avvitato*.'], 'Scegli giocattoli con il vano batterie chiuso a vite, e tieni batterie nuove e scariche fuori dalla portata dei bambini.', 'giocattolo', [['Vano a vite', .3], ['Anche le scariche', .8]]),
  FINE]),
'cadute-anziani': E('Cadute degli anziani', 11, [
  S('Cadute', ['Se un anziano','*cade*.'], 'Cadute degli anziani in casa: cosa fare, e come prevenirle.', 'caduta'),
  S('Calma', ['Non tirarlo','*su* subito.'], 'Non tirarlo su di colpo. Prima tranquillizzalo, e chiedigli come sta.', 'no-tirare', [['Niente fretta', .4]]),
  S('Le domande', ['Dove ti','fa *male*?'], 'Chiedi se ha dolore, se ha battuto la testa, se ricorda cosa è successo, e guarda se è confuso.', 'domande', [['Dolore?', .2], ['La testa?', .4], ['Ricorda?', .65]]),
  S('Quando chiamare', ['Chiama','il *112*.'], 'Chiama '+U12+' se ha battuto la testa, se prende anticoagulanti, se ha un dolore forte all\'anca o non riesce a muovere una gamba, o se è confuso.', 'telefono', [['Ha battuto la testa', .2], ['Anticoagulanti', .4], ['Dolore all\'anca', .6], ['Confuso', .9]],
    sub='Chiama il 112 se ha battuto la testa, se prende anticoagulanti, se ha un dolore forte all\'anca o non riesce a muovere una gamba, o se è confuso.'),
  S('Se sta bene', ['Su,','a *tappe*.'], 'Se sta bene, aiutalo ad alzarsi a tappe: prima su un fianco, poi in ginocchio, poi appoggiato a una sedia robusta.', 'rialzarsi', [['Su un fianco', .3], ['In ginocchio', .5], ['La sedia', .8]]),
  S('Se non si alza', ['Al caldo,','*aspetta*.'], 'Se non riesce ad alzarsi, non forzarlo: mettigli un cuscino sotto la testa, coprilo e aspetta i soccorsi.', 'coperta', [['Non forzare', .2], ['Cuscino e coperta', .6]]),
  S('Le ore dopo', ['Tienilo','d\'*occhio*.'], 'Anche se sembra a posto, controllalo nelle ore successive, soprattutto se ha battuto la testa.', 'ore-dopo', [['Nelle ore dopo', .4]]),
  S('Previeni', ['Una casa','*sicura*.'], 'Per prevenire: via i tappeti scivolosi, luci accese di notte, maniglioni in bagno, scarpe chiuse e un telefono sempre a portata di mano.', 'casa-sicura', [['Niente tappeti', .15], ['Luci di notte', .3], ['Maniglioni', .45], ['Telefono vicino', .85]]),
  FINE]),
'botti': E('Botti di Capodanno', 12, [
  S('Botti', ['Capodanno,','*senza* danni.'], 'Botti di Capodanno: ogni anno mani, occhi e ustioni al pronto soccorso. Ecco come evitarlo.', 'petardo'),
  S('Solo a norma', ['Solo','marchio *CE*.'], 'Compra solo fuochi con il marchio CE, nei negozi autorizzati, e segui le istruzioni.', 'ce', [['Marchio CE', .3], ['Negozi autorizzati', .6]]),
  S('Mai raccoglierli', ['Inesplosi?','*Lontano*.'], 'Non raccogliere mai un petardo inesploso e non riaccenderlo: può scoppiare in mano.', 'petardo-vieto', [['Non raccogliere', .3], ['Non riaccendere', .6]]),
  S('Ustione', ['20 minuti','di *acqua*.'], 'Per un\'ustione, acqua corrente fresca per almeno venti minuti, poi copri con pellicola o garza pulita.', 'rubinetto', [['Almeno 20 minuti', .5]],
    sub='Per un\'ustione, acqua corrente fresca per almeno 20 minuti, poi copri con pellicola o garza pulita.'),
  S('Mano ferita', ['Premi','e *chiama*.'], 'Se la mano sanguina, premi forte con una garza o un panno pulito e chiama '+U12+'.', 'premi', [['Premi forte', .4], ['Chiama il 112', .8, 1]],
    sub='Se la mano sanguina, premi forte con una garza o un panno pulito e chiama il 112.'),
  S('Dito staccato', ['In un','*sacchetto*.'], 'Se un dito si è staccato, mettilo in un sacchetto pulito e chiuso, e il sacchetto nel ghiaccio. Mai il dito a contatto con il ghiaccio.', 'amputazione', [['Sacchetto pulito', .3], ['Poi nel ghiaccio', .55], ['Mai a contatto', .85]]),
  S('Occhio', ['Non','*strofinare*.'], 'Se colpisce un occhio, non strofinarlo e non togliere frammenti. Coprilo senza premere e chiama '+U12+'.', 'occhio-ferito', [['Non strofinare', .2], ['Non togliere frammenti', .45], ['Copri senza premere', .7]],
    sub='Se colpisce un occhio, non strofinarlo e non togliere frammenti. Coprilo senza premere e chiama il 112.'),
  S('I bambini', ['Bambini','*lontani*.'], 'I bambini guardano da lontano: niente botti in mano ai più piccoli.', 'bimbi-lontano', [['Guardano da lontano', .5]]),
  FINE]),
'cassetta': E('La cassetta di primo soccorso', 13, [
  S('La cassetta', ['Pronti','a *tutto*.'], 'La cassetta di primo soccorso: cosa tenere in casa e in auto.', 'cassetta'),
  S('Cosa c\'è', ['Le cose','*essenziali*.'], 'Guanti, garze sterili, bende, cerotti, forbici, un disinfettante, il ghiaccio istantaneo e una coperta isotermica.', 'cassetta-contenuto', [['Guanti', .1], ['Garze e bende', .25], ['Forbici', .45], ['Ghiaccio istantaneo', .7], ['Coperta isotermica', .9]]),
  S('I numeri', ['Il foglio','dei *numeri*.'], 'Aggiungi un foglio con i numeri utili: il 112, il Centro Antiveleni e il tuo medico.', 'foglio-numeri', [['112', .3, 1], ['Centro Antiveleni', .55], ['Medico', .85]]),
  S('In auto', ['Anche','in *auto*.'], 'In auto, insieme alla cassetta, tieni sempre il giubbotto catarifrangente e il triangolo.', 'auto-kit', [['Giubbotto', .55], ['Triangolo', .8]]),
  S('Le scadenze', ['Controlla','le *scadenze*.'], 'Una volta all\'anno controlla le scadenze e rimetti quello che hai usato.', 'scadenza', [['Una volta all\'anno', .4]]),
  S('Dove tenerla', ['A portata,','*al sicuro*.'], 'Tienila in un posto facile da raggiungere per gli adulti, ma fuori dalla portata dei bambini. E niente farmaci di altri.', 'armadietto', [['A portata degli adulti', .3], ['Lontana dai bambini', .65]]),
  S('La cosa più utile', ['Sapere','*cosa fare*.'], 'Lo strumento più utile però sei tu: sapere cosa fare, e chiamare subito '+U12+'.', 'corso', [['Chiama il 112', .8, 1]],
    sub='Lo strumento più utile però sei tu: sapere cosa fare, e chiamare subito il 112.'),
  S('Buon Natale', ['Buone','*feste*.'], 'Grazie per averci seguito. Buon Natale e buon anno dalla Misericordia di Ariccia.', 'stella'),
  FINE]),
}
