# Approfondimenti «Primo soccorso passo passo» (linee guida IRC/ERC 2025, cap. BLS e Primo soccorso).
# Scena: chip, title (*parola* = giallo), voce (per Piper: numeri in lettere), sub (a schermo, se diverso),
# tags [[testo, momento 0-1, sos?]], ill = disegno animato, conta = simulazione compressioni.
FINE = dict(chip='Impara con noi', title=['Le manovre si','*imparano* provando.'], voce='Le manovre si imparano davvero provando, con un istruttore. Vieni ai corsi della Misericordia di Ariccia.', ill='fine')
def S(chip, title, voce, ill, tags=None, sub=None, **kw):
    d = dict(chip=chip, title=title, voce=voce, ill=ill, tags=tags or [], **kw)
    if sub: d['sub'] = sub
    return d
U12 = 'il uno uno due'
V = {
'ictus': dict(nome='Ictus', scene=[
  S('Ictus', ['Ogni minuto','*conta*.'], 'Ictus: riconoscerlo subito salva il cervello. Ogni minuto conta.', 'cervello'),
  S('1 · Il viso', ['Chiedi di','*sorridere*.'], 'Primo controllo, il viso. Chiedi alla persona di sorridere. Se un lato della bocca resta giù, è un segnale.', 'viso', [['Bocca storta', .75]]),
  S('2 · Le braccia', ['Chiedi di','*alzarle*.'], 'Secondo, le braccia. Chiedi di alzarle tutte e due e di tenerle su qualche secondo. Se una scende, o non si muove, è un segnale.', 'braccia', [['Un braccio scende', .8]]),
  S('3 · La parola', ['Fagli ripetere','una *frase*.'], 'Terzo, la parola. Chiedi di ripetere una frase semplice. Se parla male, non trova le parole o non capisce, è un segnale.', 'parola', [['Parole confuse', .75]]),
  S('Altri segni', ['Segni','*improvvisi*.'], 'Altri segni improvvisi: perdita della vista, perdita dell\'equilibrio, un mal di testa fortissimo, mai provato prima.', 'altri-ictus', [['Vista', .2], ['Equilibrio', .45], ['Mal di testa', .7]]),
  S('Chiama', ['Chiama','il *112*.'], 'Basta un solo segno, anche se poi passa: chiama subito '+U12+', e segna l\'ora in cui è iniziato. Serve ai medici per scegliere la cura.', 'telefono-ora', [['Chiama il 112', .3, 1], ['Segna l\'ora', .65]],
    sub='Basta un solo segno, anche se poi passa: chiama subito il 112, e segna l\'ora in cui è iniziato. Serve ai medici per scegliere la cura.'),
  S('Cosa non fare', ['Niente','in *bocca*.'], 'Non dare da mangiare, da bere o medicine, nemmeno l\'aspirina: potrebbe non riuscire a deglutire.', 'no-bocca', [['Niente cibo', .15], ['Niente acqua', .3], ['Niente farmaci', .5]]),
  S('Mentre aspetti', ['Resta','*con lui*.'], 'Resta con lui e rassicuralo. Se perde conoscenza ma respira normalmente, mettilo in posizione laterale di sicurezza.', 'pls', [['Posizione laterale di sicurezza', .7]]),
  FINE]),
'infarto': dict(nome='Infarto', scene=[
  S('Infarto', ['Il tempo','è *cuore*.'], 'Infarto: prima arrivano le cure, più cuore si salva.', 'cuore'),
  S('Il dolore', ['Un peso al','*centro* del petto.'], 'Il segno tipico è un dolore, un peso o una morsa al centro del petto. Può andare verso un braccio, il collo, la mandibola, la schiena o lo stomaco.', 'dolore', [['Braccio', .55], ['Mandibola', .65], ['Schiena', .75], ['Stomaco', .85]]),
  S('Gli altri segni', ['Sudore, nausea,','*fiato* corto.'], 'Spesso arrivano anche sudore freddo, nausea, fiato corto e una forte debolezza.', 'sudore', [['Sudore freddo', .2], ['Nausea', .4], ['Fiato corto', .6]]),
  S('Attenzione', ['Segni','*sfumati*.'], 'Nelle donne, negli anziani e in chi ha il diabete i segni possono essere più sfumati: stanchezza, fiato corto, nausea. Non sottovalutarli.', 'tre-persone', [['Donne', .2], ['Anziani', .3], ['Diabete', .42]]),
  S('Non aspettare', ['Chiama','il *112*.'], 'Se il dolore dura più di qualche minuto, o va e viene, chiama subito '+U12+'. Non aspettare che passi da solo.', 'telefono-timer', [['Chiama il 112', .6, 1]],
    sub='Se il dolore dura più di qualche minuto, o va e viene, chiama subito il 112. Non aspettare che passi da solo.'),
  S('Niente auto', ['Meglio','l\'*ambulanza*.'], 'Non accompagnarlo in auto: l\'ambulanza inizia le cure già durante il viaggio e lo porta nell\'ospedale giusto.', 'ambulanza', [['Niente auto', .2], ['Cure già in viaggio', .6]]),
  S('Mentre aspetti', ['Seduto','e a *riposo*.'], 'Fallo stare seduto o semiseduto, a riposo, e allenta i vestiti stretti. Medicine solo se lo dice l\'operatore del '+U12[3:]+'.', 'seduto', [['Seduto', .15], ['Vestiti allentati', .45], ['Farmaci: chiedi al 112', .85]],
    sub='Fallo stare seduto o semiseduto, a riposo, e allenta i vestiti stretti. Medicine solo se lo dice l\'operatore del 112.'),
  S('Se peggiora', ['Pronto alla','*rianimazione*.'], 'Se perde conoscenza e non respira normalmente, inizia subito la rianimazione e fatti portare un defibrillatore.', 'rcp-mini', [['Rianimazione', .45], ['Defibrillatore', .8]]),
  FINE]),
'emorragia': dict(nome='Emorragia', scene=[
  S('Emorragia', ['Ogni secondo','*conta*.'], 'Emorragia grave: ogni secondo conta.', 'goccia'),
  S('Proteggiti', ['Prima','i *guanti*.'], 'Prima di tutto, proteggi te stesso: se hai i guanti, indossali.', 'guanti', [['Guanti', .6]]),
  S('Premi', ['Premi','*forte*.'], 'Metti una garza, o un panno pulito, direttamente sulla ferita, e premi forte con la mano.', 'premi', [['Garza o panno pulito', .3], ['Pressione diretta', .75]]),
  S('Non mollare', ['Almeno','*10 minuti*.'], 'Mantieni la pressione per almeno dieci minuti, senza sollevare la garza per controllare.', 'premi-timer', [['Non sollevare', .75]],
    sub='Mantieni la pressione per almeno 10 minuti, senza sollevare la garza per controllare.'),
  S('Se passa', ['Aggiungi,','non *togliere*.'], 'Se il sangue passa, non togliere la garza: aggiungine un\'altra sopra e continua a premere.', 'garze', [['Garza sopra garza', .6]]),
  S('Oggetti', ['Non','*estrarre*.'], 'Se nella ferita c\'è un oggetto conficcato, non toglierlo: premi ai lati.', 'oggetto', [['Lascialo dov\'è', .45], ['Premi ai lati', .8]]),
  S('Chiama', ['Chiama','il *112*.'], 'Chiama '+U12+', o fallo chiamare, e metti il vivavoce: così puoi continuare a premere.', 'telefono-premi', [['Chiama il 112', .2, 1], ['Vivavoce', .65]],
    sub='Chiama il 112, o fallo chiamare, e metti il vivavoce: così puoi continuare a premere.'),
  S('Laccio emostatico', ['Se non','si *ferma*.'], 'Se il sangue da un braccio o da una gamba non si ferma, chi è addestrato può usare un laccio emostatico: cinque o sette centimetri sopra la ferita, segnando l\'ora.', 'laccio', [['Solo se addestrato', .3], ['5-7 cm sopra', .7], ['Segna l\'ora', .9]],
    sub='Se il sangue da un braccio o da una gamba non si ferma, chi è addestrato può usare un laccio emostatico: 5-7 cm sopra la ferita, segnando l\'ora.'),
  S('Shock', ['Sdraiato','e al *caldo*.'], 'Se è pallido, sudato e confuso, potrebbe essere in shock: fallo stare sdraiato e coprilo, per tenerlo al caldo.', 'coperta', [['Sdraiato', .6], ['Coperto', .85]]),
  FINE]),
'rianimazione': dict(nome='Rianimazione', bpm=110, scene=[
  S('Arresto cardiaco', ['Tu puoi','*salvarlo*.'], 'Arresto cardiaco: nei primi minuti, chi è vicino può fare la differenza. Vediamo come, passo passo.', 'cuore-ecg'),
  S('1 · Sicurezza', ['Il posto','è *sicuro*?'], 'Prima controlla che il posto sia sicuro, per te e per lui.', 'sicurezza', [['Traffico', .3], ['Corrente', .5], ['Fumo', .7]]),
  S('2 · Risponde?', ['Chiamalo','e *scuotilo*.'], 'Scuotilo leggermente per le spalle e chiamalo ad alta voce. Non risponde?', 'scuoti', [['Non risponde', .85]]),
  S('3 · Respira?', ['Guarda','se *respira*.'], 'Guarda se respira normalmente, per non più di dieci secondi. Respiri rari e rumorosi, come singhiozzi, non sono un respiro normale.', 'respiro', [['Massimo 10 secondi', .3], ['Singhiozzi: non è respiro', .8]],
    sub='Guarda se respira normalmente, per non più di 10 secondi. Respiri rari e rumorosi, come singhiozzi, non sono un respiro normale.'),
  S('4 · Chiama', ['112 e','*defibrillatore*.'], 'Chiama '+U12+' e metti il vivavoce: l\'operatore ti guida. Fatti portare un defibrillatore, il di a e, se c\'è.', 'telefono-dae', [['Chiama il 112', .2, 1], ['Vivavoce', .45], ['DAE', .85]],
    sub='Chiama il 112 e metti il vivavoce: l\'operatore ti guida. Fatti portare un defibrillatore, il DAE, se c\'è.'),
  S('5 · Le mani', ['Al centro','del *petto*.'], 'Inginocchiati al suo fianco. Mani una sopra l\'altra, al centro del petto. Braccia tese, spalle sopra le mani.', 'mani', [['Centro del petto', .45], ['Braccia tese', .8]]),
  S('6 · Compressioni', ['Segui il','*ritmo*.'], 'Spingi forte, cinque o sei centimetri, e lascia risalire il torace. Segui il ritmo.', 'rcp-sim', [['5-6 cm', .3], ['110 al minuto', .9]], conta=30,
    sub='Spingi forte, 5-6 centimetri, e lascia risalire il torace. Segui il ritmo.'),
  S('7 · Ventilazioni', ['Compressioni','e *ventilazioni*.'], 'Se sai farlo, dopo trenta compressioni dai due ventilazioni. Altrimenti, continua solo con le compressioni, senza fermarti.', 'ventila', [['Se sai farlo: 30 e 2', .3], ['Se no: solo compressioni', .8]],
    sub='Se sai farlo, dopo 30 compressioni dai 2 ventilazioni. Altrimenti, continua solo con le compressioni, senza fermarti.'),
  S('8 · Il DAE', ['Segui','la sua *voce*.'], 'Quando arriva il defibrillatore, accendilo e segui la sua voce. Attacca le piastre come nel disegno. Durante l\'analisi e la scarica, nessuno deve toccare la persona.', 'dae', [['Accendilo', .15], ['Piastre', .45], ['Nessuno lo tocchi', .85, 1]]),
  S('9 · Non fermarti', ['Fino ai','*soccorsi*.'], 'Poi riprendi subito le compressioni, e non fermarti finché non arrivano i soccorsi o finché non si sveglia. Se siete in due, datevi il cambio ogni due minuti.', 'cambio', [['Riprendi subito', .2], ['Cambio ogni 2 minuti', .85]],
    sub='Poi riprendi subito le compressioni, e non fermarti finché non arrivano i soccorsi o finché non si sveglia. Se siete in due, datevi il cambio ogni 2 minuti.'),
  FINE]),
'soffocamento': dict(nome='Soffocamento', scene=[
  S('Soffocamento', ['Cosa fare','in un *adulto*.'], 'Soffocamento in un adulto: cosa fare, passo passo.', 'gola'),
  S('Tossisce?', ['Lascialo','*tossire*.'], 'Se tossisce e riesce a parlare, incoraggialo a tossire forte, e resta con lui.', 'tosse', [['Incoraggia la tosse', .55]]),
  S('Ostruzione grave', ['Non parla,','non *respira*.'], 'Se non riesce più a tossire, a parlare o a respirare, e si porta le mani alla gola, devi agire subito.', 'gola', [['Mani alla gola', .6], ['Agisci subito', .85, 1]]),
  S('5 colpi', ['Tra le','*scapole*.'], 'Mettiti di lato, sostienilo con una mano sul petto e piegalo in avanti. Con il palmo dell\'altra mano, dai fino a cinque colpi forti tra le scapole.', 'colpi', [['Piegato in avanti', .35], ['Fino a 5 colpi', .8]]),
  S('5 compressioni', ['Spingi','*dentro* e in su.'], 'Se non basta, mettiti dietro di lui: pugno appena sopra l\'ombelico, coperto dall\'altra mano. Tira con forza verso di te e verso l\'alto, fino a cinque volte.', 'addome', [['Sopra l\'ombelico', .35], ['Dentro e in su', .7], ['Fino a 5 volte', .9]]),
  S('Alterna', ['5 e 5,','senza *fermarti*.'], 'Continua alternando cinque colpi e cinque compressioni, finché l\'oggetto non esce.', 'alterna', [['Alterna 5 e 5', .6]]),
  S('Se sviene', ['112 e','*rianimazione*.'], 'Se perde conoscenza, accompagnalo a terra, chiama '+U12+' e inizia la rianimazione.', 'rcp-mini', [['Chiama il 112', .55, 1], ['Rianimazione', .85]],
    sub='Se perde conoscenza, accompagnalo a terra, chiama il 112 e inizia la rianimazione.'),
  S('Dopo', ['Sempre','dal *medico*.'], 'Dopo le compressioni addominali, fallo sempre visitare da un medico. Nei bambini piccoli le manovre sono diverse: si imparano a un corso.', 'medico', [['Visita medica', .3], ['Bambini: manovre diverse', .8]]),
  FINE]),
'anafilassi': dict(nome='Anafilassi', scene=[
  S('Anafilassi', ['L\'allergia','*grave*.'], 'Anafilassi: la reazione allergica grave. Agire in fretta salva la vita.', 'adrenalina'),
  S('Le cause', ['In pochi','*minuti*.'], 'Può arrivare in pochi minuti, dopo un cibo, una puntura d\'insetto o un farmaco.', 'cause', [['Cibo', .4], ['Puntura', .6], ['Farmaco', .8]]),
  S('I segni', ['Riconosci','i *segni*.'], 'Gonfiore di labbra, lingua o gola. Fatica a respirare, voce rauca, fischi. Orticaria. Pallore, debolezza, svenimento.', 'corpo-segni', [['Gonfiore', .1], ['Respiro', .35], ['Orticaria', .6], ['Svenimento', .85]]),
  S('Chiama', ['Chiama','il *112*.'], 'Chiama subito '+U12+', e di\' che sospetti una reazione allergica grave.', 'telefono', [['Chiama il 112', .3, 1], ['Allergia grave', .75]],
    sub='Chiama subito il 112, e di\' che sospetti una reazione allergica grave.'),
  S('Adrenalina', ['L\'autoiniettore','sulla *coscia*.'], 'Se ha l\'autoiniettore di adrenalina, aiutalo a usarlo: sulla parte esterna della coscia, anche sopra i vestiti, tenendolo premuto per il tempo indicato.', 'penna', [['Esterno coscia', .4], ['Anche sui vestiti', .6], ['Il tempo indicato', .88]]),
  S('La posizione', ['Seduto','o *sdraiato*.'], 'Se respira male, fallo stare seduto. Se è debole o pallido, sdraiato con le gambe sollevate. Non farlo alzare in piedi all\'improvviso.', 'posizioni', [['Respira male: seduto', .2], ['Debole: gambe su', .55], ['Non alzarlo', .85]]),
  S('Dopo 5 minuti', ['La seconda','*dose*.'], 'Se dopo cinque minuti non migliora e ha una seconda dose, si può ripetere.', 'penna-timer', [['Seconda dose dopo 5 minuti', .7]],
    sub='Se dopo 5 minuti non migliora e ha una seconda dose, si può ripetere.'),
  S('Se non respira', ['Pronto alla','*rianimazione*.'], 'Se perde conoscenza e non respira normalmente, inizia la rianimazione.', 'rcp-mini', [['Rianimazione', .8]]),
  FINE]),
'ustioni': dict(nome='Ustioni', scene=[
  S('Ustioni', ['Raffredda','*subito*.'], 'Ustioni: i primi minuti decidono quanto sarà grave.', 'ustione'),
  S('Ferma il fuoco', ['Fermati, sdraiati,','*rotola*.'], 'Prima ferma la causa. Se i vestiti prendono fuoco: fermati, sdraiati e rotola, o copri con una coperta.', 'rotola', [['Fermati', .35], ['Sdraiati', .5], ['Rotola', .65]]),
  S('Acqua', ['20 minuti','di *acqua*.'], 'Metti subito la parte sotto acqua corrente fresca, non ghiacciata, per almeno venti minuti.', 'rubinetto', [['Acqua fresca', .4], ['Almeno 20 minuti', .85]],
    sub='Metti subito la parte sotto acqua corrente fresca, non ghiacciata, per almeno 20 minuti.'),
  S('Anelli', ['Via anelli','e *orologi*.'], 'Togli anelli, orologi e braccialetti prima che la parte si gonfi. Non staccare i vestiti attaccati alla pelle.', 'anelli', [['Via anelli', .25], ['Vestiti attaccati: lasciali', .8]]),
  S('Copri', ['Pellicola,','*senza* stringere.'], 'Poi copri con pellicola trasparente per alimenti, senza stringere, o con una garza pulita che non si attacca.', 'pellicola', [['Pellicola per alimenti', .4], ['Senza stringere', .6]]),
  S('Cosa non fare', ['Niente','*rimedi*.'], 'Niente ghiaccio, burro, olio o dentifricio. E non bucare le bolle.', 'no-rimedi', [['Niente ghiaccio', .15], ['Niente burro', .3], ['Bolle: non bucarle', .8]]),
  S('Al caldo', ['Raffredda la ferita,','*scalda* lui.'], 'Raffredda la ferita, ma tieni al caldo il resto del corpo, soprattutto nei bambini.', 'coperta-braccio', [['Il corpo al caldo', .5], ['Attenzione ai bambini', .85]]),
  S('Quando chiamare', ['Chiama','il *112*.'], 'Chiama '+U12+' se l\'ustione è più grande del palmo della sua mano, se è sul viso, sulle mani o sui genitali, se è elettrica o chimica, se ha respirato fumo, o se è un bambino o un anziano.', 'palmo', [['Più grande del palmo', .2], ['Viso, mani', .35], ['Elettrica o chimica', .55], ['Fumo', .7], ['Bambini e anziani', .88]],
    sub='Chiama il 112 se l\'ustione è più grande del palmo della sua mano, se è sul viso, sulle mani o sui genitali, se è elettrica o chimica, se ha respirato fumo, o se è un bambino o un anziano.'),
  FINE]),
'ipoglicemia': dict(nome='Ipoglicemia', scene=[
  S('Ipoglicemia', ['Lo zucchero','è *troppo* basso.'], 'Ipoglicemia: quando lo zucchero nel sangue scende troppo.', 'zucchero'),
  S('A chi succede', ['Chi ha','il *diabete*.'], 'Succede soprattutto a chi ha il diabete e usa insulina o alcune medicine: dopo un pasto saltato, uno sforzo, o troppo farmaco.', 'glucometro', [['Pasto saltato', .55], ['Sforzo', .7], ['Troppo farmaco', .88]]),
  S('I segni', ['Riconosci','i *segni*.'], 'I segni: sudore, tremore, pallore, fame, mal di testa. Poi confusione, o un comportamento strano, che può sembrare ubriachezza.', 'tremore', [['Sudore', .1], ['Tremore', .2], ['Confusione', .6], ['Sembra ubriaco', .85]]),
  S('Zucchero', ['Zucchero','*subito*.'], 'Se è sveglio e riesce a deglutire, dagli subito zucchero: compresse di glucosio, un succo di frutta o una bibita zuccherata, non light, oppure tre o quattro zollette.', 'zuccheri', [['Sveglio e deglutisce', .2], ['Glucosio', .4], ['Succo o bibita', .6], ['3-4 zollette', .9]],
    sub='Se è sveglio e riesce a deglutire, dagli subito zucchero: compresse di glucosio, un succo di frutta o una bibita zuccherata, non light, oppure 3-4 zollette.'),
  S('Dopo 15 minuti', ['Non migliora?','*Ripeti*.'], 'Aspetta quindici minuti. Se non migliora, dagli altro zucchero.', 'timer15', [['Ripeti', .8]],
    sub='Aspetta 15 minuti. Se non migliora, dagli altro zucchero.'),
  S('Poi', ['Qualcosa','da *mangiare*.'], 'Quando sta meglio, fagli mangiare qualcosa: pane, crackers, o il pasto, se è ora.', 'merenda', [['Pane o crackers', .6]]),
  S('Non risponde', ['Niente','in *bocca*.'], 'Se non risponde o non riesce a deglutire, niente in bocca: rischia di soffocare. Chiama '+U12+' e, se respira, mettilo in posizione laterale di sicurezza.', 'pls', [['Niente in bocca', .2], ['Chiama il 112', .55, 1], ['Posizione laterale', .9]],
    sub='Se non risponde o non riesce a deglutire, niente in bocca: rischia di soffocare. Chiama il 112 e, se respira, mettilo in posizione laterale di sicurezza.'),
  FINE]),
'avvelenamento': dict(nome='Avvelenamento', scene=[
  S('Avvelenamento', ['Niente','*fai da te*.'], 'Avvelenamento: i rimedi fai da te possono peggiorare le cose.', 'veleno'),
  S('Dove succede', ['Quasi sempre','in *casa*.'], 'La maggior parte degli avvelenamenti succede in casa: detersivi, farmaci, prodotti per il giardino. I bambini sono i più a rischio.', 'casa', [['Detersivi', .2], ['Farmaci', .3], ['Bambini', .85]]),
  S('Non far vomitare', ['Niente','*vomito*.'], 'Non provocare il vomito: un prodotto corrosivo, risalendo, brucia di nuovo.', 'no-vomito', [['Niente vomito', .4]]),
  S('Niente da bere', ['Niente','*latte*.'], 'Non dare latte, acqua o altro da bere, se non lo dice il Centro Antiveleni.', 'no-latte', [['Niente latte', .2], ['Niente acqua', .35]]),
  S('Chiama', ['112 o','*Antiveleni*.'], 'Chiama '+U12+' o un Centro Antiveleni: rispondono giorno e notte.', 'cav', [['Chiama il 112', .15, 1], ['Centro Antiveleni', .5]],
    sub='Chiama il 112 o un Centro Antiveleni: rispondono giorno e notte.'),
  S('A Roma', ['I numeri','da *salvare*.'], 'A Roma: Gemelli, zero sei, tre zero cinque, quattro tre quattro tre. Umberto primo, zero sei, quattro nove nove sette, otto zero zero zero. Per i bambini, Bambino Gesù, zero sei, sei otto cinque nove, tre sette due sei.', 'cav', [['Gemelli 06 305 4343', .1], ['Umberto I 06 4997 8000', .4], ['Bambino Gesù 06 6859 3726', .7]],
    sub='A Roma, giorno e notte: Gemelli 06 305 4343 · Umberto I 06 4997 8000 · per i bambini, Bambino Gesù 06 6859 3726.'),
  S('La confezione', ['Tienila','in *mano*.'], 'Tieni a portata di mano la confezione, e di\' cosa ha preso, quanto e quando.', 'confezione', [['Cosa', .55], ['Quanto', .7], ['Quando', .85]]),
  S('Pelle e occhi', ['Sciacqua','a *lungo*.'], 'Su pelle o occhi: togli i vestiti contaminati e sciacqua a lungo con acqua corrente.', 'occhi', [['Via i vestiti', .35], ['Acqua corrente', .8]]),
  S('Gas e fumi', ['Aria','*aperta*.'], 'Gas o fumi, come il monossido di carbonio: apri le finestre e porta la persona all\'aria aperta, solo se non rischi anche tu.', 'finestra', [['Apri le finestre', .55], ['Senza rischi per te', .88]]),
  S('Previeni', ['Lontano','dai *bambini*.'], 'Per prevenire: prodotti nelle confezioni originali, chiusi e in alto, lontano dai bambini. Mai in bottiglie da bibita.', 'armadietto', [['Confezioni originali', .2], ['In alto', .45], ['Mai nelle bottiglie', .85]]),
  FINE]),
'trauma-cranico': dict(nome='Trauma cranico', scene=[
  S('Trauma cranico', ['Dopo un colpo','alla *testa*.'], 'Colpo alla testa: cosa osservare, e quando preoccuparsi.', 'testa'),
  S('Fermati', ['Nel dubbio,','*fuori* dal campo.'], 'Dopo un colpo alla testa, fermati subito. Nello sport la regola è: nel dubbio, fuori dal campo.', 'campo', [['Stop', .3], ['Nel dubbio, fuori', .8]]),
  S('Osserva', ['Risponde?','*Ricorda*?'], 'Osserva bene la persona: risponde? Sa dove si trova? Ricorda cosa è successo?', 'domande', [['Risponde?', .2], ['Dove si trova?', .45], ['Ricorda?', .75]]),
  S('Segnali d\'allarme', ['Quando chiamare','il *112*.'], 'Chiama '+U12+' se ha perso conoscenza, vomita più volte, è confuso o molto assonnato, se il mal di testa peggiora o se ha convulsioni.', 'allarme', [['Svenimento', .25], ['Vomito ripetuto', .4], ['Sonnolenza', .58], ['Mal di testa che peggiora', .75], ['Convulsioni', .92]],
    sub='Chiama il 112 se ha perso conoscenza, vomita più volte, è confuso o molto assonnato, se il mal di testa peggiora o se ha convulsioni.'),
  S('Altri segnali', ['Guarda','anche *qui*.'], 'E anche se esce sangue o liquido chiaro dal naso o dalle orecchie, se le pupille sono diverse, o se un braccio o una gamba sono deboli.', 'pupille', [['Naso e orecchie', .3], ['Pupille diverse', .6], ['Debolezza', .85]]),
  S('Collo e schiena', ['Non','*muoverlo*.'], 'Se pensi che si sia fatto male al collo o alla schiena, non muoverlo, a meno che non sia in pericolo.', 'non-muovere', [['Non muoverlo', .55]]),
  S('Il bernoccolo', ['Ghiaccio','nel *panno*.'], 'Per il bernoccolo, ghiaccio avvolto in un panno, mai direttamente sulla pelle.', 'ghiaccio', [['Mai sulla pelle', .75]]),
  S('Dal medico', ['Anche se','sta *bene*.'], 'Fallo vedere da un medico anche se sta bene, soprattutto se è anziano o prende anticoagulanti.', 'medico', [['Anziani', .65], ['Anticoagulanti', .85]]),
  S('Le ore dopo', ['Non lasciarlo','*solo*.'], 'Nelle ventiquattro ore dopo, non lasciarlo solo. Niente alcol, niente guida, e riposo.', 'notte', [['24 ore', .2], ['Niente alcol', .55], ['Niente guida', .7], ['Riposo', .85]],
    sub='Nelle 24 ore dopo, non lasciarlo solo. Niente alcol, niente guida, e riposo.'),
  FINE]),
}

from contenuti2 import V2
V.update(V2)
from contenuti3 import V3
V.update(V3)
